### ISSUE TITLE
incorrect S3 hostname

### ISSUE THREAD

**Issue by namotco** [pplu/AWSv4Signer#2]
https://s3-us-east-1.amazonaws.com/ does not exist
See here:
https://stackoverflow.com/questions/26604977/url-for-public-amazon-s3-bucket

https://github.com/pplu/AWSv4Signer/blob/9f31fbf1ee51fef255805de5a2b669b6ec85a5f9/lib/Signer/AWSv4/S3.pm#L17

**Comment by namotco** [comment]
In my testing, this fixed it:
```
  has bucket_host => (is => 'ro', isa => Str, init_arg => undef, lazy => 1, default => sub {
    my $self = shift;
    if ($self->region =~m/east-us-1/i) {
      return 's3.amazonaws.com';
    } else {
      return 's3-' . $self->region . '.amazonaws.com';
    }
  });

```

**Comment by pplu** [comment]
Hi,

    Version 0.05 has just been released to CPAN with your fix included. Thank you for your contribution :bow:
